### ISSUE TITLE
聚类任务和分类任务中使用的数据

### ISSUE THREAD

**Issue by dugzzuli** [YuxiangRen/Heterogeneous-Deep-Graph-Infomax#11]
您好。我想请问一下，以acm为例，聚类任务中,用于聚类测试 数据是全部的数据还是仅仅是test的数据；分类任务中，训练数据为20%和80%，这个是全部数据的还是test数据的。非常感谢您。

**Comment by YuxiangRen** [comment]
你好，用于聚类的是全部数据。哪个数据集的划分是仅用于在分类任务中训练classifier的，对于HDGI和其他一些无监督的方法来说，训练集和representation
learning的过程是无关的。

Best wishes!

Yuxiang Ren

**Comment by dugzzuli** [comment]
非常感谢您的解答。[cid:image001.png@01D676D1.01F368A0]

Best wishes!
King Du

发件人: YuxiangRen <notifications@github.com>
发送时间: 2020年8月19日 星期三 23:06
收件人: YuxiangRen/Heterogeneous-Deep-Graph-Infomax <Heterogeneous-Deep-Graph-Infomax@noreply.github.com>
抄送: dug <bingwei2642@outlook.com>; Author <author@noreply.github.com>
主题: Re: [YuxiangRen/Heterogeneous-Deep-Graph-Infomax] 聚类任务和分类任务中使用的数据 (#11)

你好，用于聚类的是全部数据。哪个数据集的划分是仅用于在分类任务中训练classifier的，对于HDGI和其他一些无监督的方法来说，训练集和representation
learning的过程是无关的。

Best wishes!

Yuxiang Ren
