### ISSUE TITLE
ACM dataset

### ISSUE THREAD

**Issue by lx10030802** [YuxiangRen/Heterogeneous-Deep-Graph-Infomax#12]
Great respect for your work. I want to try the two meta-paths' method. Could you please provide relevant data of ACM dataset? Thank you!

**Comment by YuxiangRen** [comment]
You can get the original data and relevant files from the link: 
https://drive.google.com/file/d/1sdCtMZbmE0u6nubI36ktaw_TKcE-3KYz/view?usp=sharing

**Comment by lx10030802** [comment]
> You can get the original data and relevant files from the link:
> https://drive.google.com/file/d/1sdCtMZbmE0u6nubI36ktaw_TKcE-3KYz/view?usp=sharing
Thank you!This link access has been denied and an application is required. I have applied for access rights
