### ISSUE TITLE
Could you please release the code of DGI experiment with any dataset?

### ISSUE THREAD

**Issue by Yonggie** [YuxiangRen/Heterogeneous-Deep-Graph-Infomax#15]
As shown in experiment in the paper, DGI perfomance is strongly competitive.
But I am very curious about its implementation, because DGI is applicable only on isomorphic graph, how could your team apply this method to a heterogeneous graph?
Thanks so much if you do release the code. If not, could you please briefly describe the experiment?

**Comment by YuxiangRen** [comment]
As we mentioned in the paper, for methods designed for homogeneous graphs, i.e., DeepWalk, DGI, GCN, GAT, we do not consider graph heterogeneity and construct meta-path based adjacency matrix, then we report the best performance. In the meta-path based adjacency matrix, only the target nodes exist which belong to the same type.
