### ISSUE TITLE
IMDB extract Edge

### ISSUE THREAD

**Issue by NlpRookie** [YuxiangRen/Heterogeneous-Deep-Graph-Infomax#6]
Hi, 
I try to run extractEdge, an error occurred

sp.coo_matrix
ValueError: column index exceeds matrix dimensions

I download this movie dataset from [https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset](url)

**Comment by YuxiangRen** [comment]
I didn't use the dataset from Kaggle. I add the original data "movie_metadata_3class.csv" to the data fold, you can check it. 

If you have other questions, just let me know.
